-- Cart + Order + Payment (Phases 2–4).

DROP TABLE IF EXISTS payment_webhook_events;
DROP TABLE IF EXISTS payment_attempts;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS carts;

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT carts_status_check CHECK (status IN ('OPEN', 'CHECKED_OUT'))
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    line_total DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT cart_items_quantity_pos CHECK (quantity > 0),
    CONSTRAINT cart_items_price_pos CHECK (price > 0),
    CONSTRAINT cart_items_line_total_pos CHECK (line_total > 0)
);

CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items (product_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_cart FOREIGN KEY (cart_id) REFERENCES carts (id),
    CONSTRAINT uq_orders_cart_id UNIQUE (cart_id),
    CONSTRAINT orders_status_check CHECK (
        status IN ('CREATED', 'PENDING_PAYMENT', 'PAYMENT_FAILED', 'PAID')
    ),
    CONSTRAINT orders_total_pos CHECK (total_amount > 0)
);

CREATE INDEX idx_orders_cart_id ON orders (cart_id);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    line_total DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT order_items_quantity_pos CHECK (quantity > 0),
    CONSTRAINT order_items_price_pos CHECK (price > 0),
    CONSTRAINT order_items_line_total_pos CHECK (line_total > 0)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);

CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    provider_reference VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_attempts_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT payment_attempts_status_check CHECK (status IN ('INITIATED', 'CONFIRMED', 'FAILED')),
    CONSTRAINT payment_attempts_amount_pos CHECK (amount > 0)
);

CREATE INDEX idx_payment_attempts_order_id ON payment_attempts (order_id);
CREATE INDEX idx_payment_attempts_order_status ON payment_attempts (order_id, status);

CREATE TABLE payment_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_event_id VARCHAR(255) NOT NULL,
    payment_attempt_id BIGINT NOT NULL,
    webhook_status VARCHAR(32) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    processing_result VARCHAR(32) NOT NULL,
    received_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_payment_webhook_provider_event_id UNIQUE (provider_event_id),
    CONSTRAINT fk_payment_webhook_attempt FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempts (id),
    CONSTRAINT payment_webhook_processing_check CHECK (
        processing_result IN ('PROCESSED', 'DUPLICATE', 'IGNORED', 'REJECTED')
    ),
    CONSTRAINT payment_webhook_amount_pos CHECK (amount > 0)
);

CREATE INDEX idx_payment_webhook_attempt_id ON payment_webhook_events (payment_attempt_id);
CREATE INDEX idx_payment_webhook_provider_event_id ON payment_webhook_events (provider_event_id);
